### ISSUE TITLE
Audio is only Loud Static

### ISSUE THREAD

**Issue by ThePapaw** [libretro/libretro-pocketcdg#20]
I am trying to set this up for the first time. I downloaded the core and when I load a cdg file it appears to work as expected, however the audio is only loud static rather then the mp3 file. When I look at sound devices in RA, all I am getting is a place to type in a name. I'm  not really sure what to do there. 

All the other cores I use work fine as far as sound goes.

**Comment by zach-morris** [comment]
Came here to note this as well.  The issue isn't present in older versions of the core, and I'm guessing it's [this](https://github.com/libretro/libretro-pocketcdg/commit/bc59f80012e2431b9021779f07cad0c7e826f243) commit that caused the issue.

**Comment by ThePapaw** [comment]
@zach-morris , thank you. I downloaded the 2yr old version on your git and it is working on my android devices. Still not working in RA though in Windows. Any chance you have an old working core?
